// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgFLU4whqoqU893OxJHqCKqmt6F7SX1WE',
    appId: '1:561058666320:web:8567bc9db01c6b3d503e55',
    messagingSenderId: '561058666320',
    projectId: 'hcm2303',
    authDomain: 'hcm2303.firebaseapp.com',
    databaseURL:
        'https://hcm2303-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hcm2303.appspot.com',
    measurementId: 'G-382LGK37ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzosHaRq0czp38ATNzC2HgtBAmc3Z1058',
    appId: '1:561058666320:android:b6ea77804ce7211d503e55',
    messagingSenderId: '561058666320',
    projectId: 'hcm2303',
    databaseURL:
        'https://hcm2303-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hcm2303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwyJA_ath-HqiTjAu9abXudbLp9x8wo_U',
    appId: '1:561058666320:ios:ccb989e4d4d54f8f503e55',
    messagingSenderId: '561058666320',
    projectId: 'hcm2303',
    databaseURL:
        'https://hcm2303-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hcm2303.appspot.com',
    iosClientId:
        '561058666320-seq1b5adkh0o0ucjhv91end8l3plcbrs.apps.googleusercontent.com',
    iosBundleId: 'com.vuongdan.hcm2303.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwyJA_ath-HqiTjAu9abXudbLp9x8wo_U',
    appId: '1:561058666320:ios:26f876564ae0085e503e55',
    messagingSenderId: '561058666320',
    projectId: 'hcm2303',
    databaseURL:
        'https://hcm2303-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hcm2303.appspot.com',
    iosClientId:
        '561058666320-mm5bc21p08jcn66mmp4ss9vifv8epsng.apps.googleusercontent.com',
    iosBundleId: 'com.example.hcm2303',
  );
}
